#;	.globl ehcmodule2
#;	.balign 32
#;ehcmodule2:
#;	.incbin "../data/ehcmodule2_elf"

	.globl dip_plugin2
	.balign 32
dip_plugin2:
	.incbin "../data/dip_plugin2_bin"

#;	.globl ehcmodule3
#;	.balign 32
#;ehcmodule3:
#;	.incbin "../data/ehcmodule3_elf"

	.globl dip_plugin3
	.balign 32
dip_plugin3:
	.incbin "../data/dip_plugin3_bin"

#;	.globl ehcmodule4
#;	.balign 32
#;ehcmodule4:
#;	.incbin "../data/ehcmodule4_elf"

	.globl dip_plugin4
	.balign 32
dip_plugin4:
	.incbin "../data/dip_plugin4_bin"

	.globl ehcmodule_frag
	.balign 32
ehcmodule_frag:
	.incbin "../data/ehcmodule_frag"

	.globl dip_plugin_249
	.balign 32
dip_plugin_249:
	.incbin "../data/dip_plugin_249"